version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/service-1.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/service-2.conf:/etc/nginx/conf.d/default.conf:ro

  service-one:
    build: .
    expose:
      - "8001"
    environment:
      - PORT=8001
    env_file:
      - microservices\service-one\.env

  service-two:
    build: .
    expose:
      - "8001"
    environment:
      - PORT=8002
    env_file:
      - microservices\service-two\.env